build: helloworld.cpp
	$(CXX) -std=c++11 -lpthread -g helloworld.cpp -o helloworld.exe

solution: helloworld-sol.cpp
	$(CXX) -std=c++11 -lpthread -g helloworld-sol.cpp -o helloworld-sol.exe

clean:
	rm -rf core*, *.exe

